# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.calcOutput = QtWidgets.QLabel(Widget)
        self.calcOutput.setGeometry(QtCore.QRect(260, 130, 251, 71))
        self.calcOutput.setStyleSheet("background-color:black;color:white")
        self.calcOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.calcOutput.setObjectName("calcOutput")
        self.calcInput = QtWidgets.QTextEdit(Widget)
        self.calcInput.setGeometry(QtCore.QRect(210, 260, 371, 31))
        self.calcInput.setObjectName("calcInput")
        self.pushButton = QtWidgets.QPushButton(Widget)
        self.pushButton.setGeometry(QtCore.QRect(590, 260, 80, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Widget)
        self.calcInput.textChanged.connect(self.calcOutput.clear)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.calcOutput.setText(_translate("Widget", "TextLabel"))
        self.pushButton.setText(_translate("Widget", "Calculate!"))

    def setup(self):
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Widget = QtWidgets.QWidget()
        ui = Ui_Widget()
        ui.setupUi(Widget)
        Widget.show()
        sys.exit(app.exec_())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
